// TYPES AS CONST SO ITS EASIER TO SPOT ERRORS
export const GET_CONFIG = 'GET_CONFIG';
export const GET_GENRES = 'GET_GENRES';
export const SELECTED_MENU = 'SELECTED_MENU';
export const FETCH_MOVIES_GENRE = 'FETCH_MOVIES_GENRE';
export const FETCH_MOVIES_DISCOVER = 'FETCH_MOVIES_DISCOVER';
