// TYPES AS CONST SO ITS EASIER TO SPOT ERRORS
export const GET_CONFIG = 'GET_CONFIG';
export const GET_GENRES = 'GET_GENRES';
export const SELECTED_MENU = 'SELECTED_MENU';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_CAST = 'FETCH_CAST';
export const FETCH_MOVIES_GENRE = 'FETCH_MOVIES_GENRE';
export const FETCH_MOVIES_DISCOVER = 'FETCH_MOVIES_DISCOVER';
export const FETCH_MOVIES_SEARCH = 'FETCH_MOVIES_SEARCH';
export const SET_HEADER = 'SET_HEADER';
export const REMOVE_HEADER = 'REMOVE_HEADER';
export const REMOVE_SELECTED_MENU = 'REMOVE_SELECTED_MENU';
export const CLEAR_PREVIOUS_MOVIES = 'CLEAR_PREVIOUS_MOVIES';
export const CLEAR_PREVIOUS_MOVIE = 'CLEAR_PREVIOUS_MOVIE';
export const FETCH_PERSON = 'FETCH_PERSON';
export const CLEAR_PREVIOUS_PERSON = 'CLEAR_PREVIOUS_PERSON';
